[project]
name = "vrmonitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "loguru>=0.7.3",
    "mediapipe>=0.10.33",
    "opencv-python>=4.13.0.92",
    "pyautogui>=0.9.54",
    "pydirectinput>=1.0.4",
    "pygrabber>=0.2",
    "pyside6>=6.11.0",
    "pyvirtualcam>=0.15.0",
]

[dependency-groups]
dev = [
    "nuitka>=4.2.2",
    "ruff>=0.15.7",
]
